### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by stereokai** [bobef/ColorSchemeEditor#1]
It doesn't show in Package Control in ST3

**Comment by bobef** [comment]
It used to be there but I deleted my account at one time. Open sublime go to menu / browse packages. Create new folder. Copy the contents of this repository (download zip button on the right) to the new folder.

**Comment by stereokai** [comment]
Thanks

**Comment by bjankord** [comment]
Any plans to add this back to Package Control?

**Comment by bobef** [comment]
No, but if someone needs it I may add it.

**Comment by bobef** [comment]
I was going to add it but someone already did - https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L1736 . Not showing in my Sublime though.
