### ISSUE TITLE
Color definitions are not highlighted by Color Highlighter

### ISSUE THREAD

**Issue by bobrocke** [bobef/ColorSchemeEditor#2]
Sublime Text 3 build 3095, Color Highlighter package v2015.09.03

**Comment by bobef** [comment]
Man, I have no idea what you mean. I don't know what is Color Highlighter.

**Comment by bobrocke** [comment]
https://github.com/Monnoroch/ColorHighlighter

**Comment by bobef** [comment]
Cool plugin but seems unrelated to this repo.

**Comment by bobrocke** [comment]
?

The window open to the color scheme being editing is just another text file and should be highlighted properly, as are all other text views.

**Comment by bobef** [comment]
Maybe, but I'm not the author of Color Highlighter. I don't care if it works or not. This is the repo of ColorSchemeEditor (which I also don't care if it works btw, it is here in case someone likes it).

**Comment by bobrocke** [comment]
OK. Deleted.
