### ISSUE TITLE
MacOSX ?

### ISSUE THREAD

**Issue by sebthiriet** [bobef/ColorSchemeEditor#3]
Hi, 
how this tool works with MacOSX ?
Shift+F12 does not work on Mac !
Is there a specific shortcut for our platform?

**Comment by bobef** [comment]
Enable your F keys or use with fn+shift+f12 (I guess). Remove the OS X shortcut for F12. Each OS X has different shortcuts. Then it works.

**Comment by bobef** [comment]
![screen shot 2015-09-12 at 08 40 41](https://cloud.githubusercontent.com/assets/13868315/9830322/063b446a-592a-11e5-8ac8-b0fed635dd72.png)

**Comment by bobef** [comment]
Or you can change the shortcut of the plugin. But Google how to do it, I don't feel like explaining now.

**Comment by caesarsol** [comment]
You also can open the Command Palette (cmd+shift+P) and search `Color Scheme Editor: Edit current color scheme`.
