### ISSUE TITLE
Why isn't this on Package Control anymore?

### ISSUE THREAD

**Issue by caesarsol** [bobef/ColorSchemeEditor#4]
I like this plugin, but it has disappeared recently, why is that?

**Comment by bobef** [comment]
I don't know man. Someone asked this recently so I tried to add it to Package Control and followed the instructions and went where I should add it and it was already there (not added by me) - https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L1790 - it is still there. I don't know why it doesn't show up. I don't have time to check with Package Control and ask them.

**Comment by caesarsol** [comment]
That's ok, I understand ;)
But the solution could be simple:
I see there is the `"tags": true` option in your link, but there is no tag in the repo.
From [here](https://packagecontrol.io/docs/submitting_a_package#Step_4) I read:

> If you are using GitHub or BitBucket for your hosting, you will need to create a tag each time you want to make a new version available to users. The tag names must be a semantic version number.
> Please note that branch-based releases have been deprecated and no new packages will be accepted that utilize that feature. Existing packages are encouraged to update to using tags.

The solution could be to tag the last commit with `v0.1`.

**Comment by bobef** [comment]
Cool, I'll tag it tomorrow when I get back to my laptop. Regards.

**Comment by caesarsol** [comment]
thanks!

**Comment by bobef** [comment]
So there is tag now. Lets see if it works :)
